### ISSUE TITLE
Videos longer than 10 seconds don't send through gallery. Error: "Failed to send"

### ISSUE THREAD

**Issue by halederrick** [rhunk/SnapEnhance#112]
### Description

I installed SnapEnhance yesterday and I'm certain that this is a bug. Let me explain:

When I open my Gallery app and share a video to open it on Snapchat (With Gallery Override activated) the video ALWAYS fail to send it it's longer than 10 seconds.

A video longer than 10 seconds only sends using Gallery Override if we open the camera roll option within a chat, BUT the video doesn't split and sends as a one single snap (Even with "Disable Snap Splitting turned off). And the result is a snap that looks fake.

I believe this is a bug because of the "fail to send" error for every single video that is longer than 10 seconds. Doesn't matter the size of the video file. 

I will post some screenshots to show the error.

### Reproduction steps

```bash
Reproduction Steps on the Screenshots below:
```

### Screenshots

![20230629_112248](https://github.com/rhunk/SnapEnhance/assets/138125942/df21b4ea-fda0-47e6-8f02-fa9a4dc6cbe4)

### Snapchat Version

12.40.0.43

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by TheVisual** [comment]
@authorisation this is fixed with latest 1.2.0 you can close this btw.

**Comment by halederrick** [comment]
> @authorisation this is fixed with latest 1.2.0 you can close this btw.

It wasn't fixed. Multiple people on the official telegram group, including one of the admins said it wasn't fixed yet. But they are working on it for the next update. 

Is it really working for you? Sharing longer videos through gallery with gallery override turned on exactly like I described in the images?

**Comment by halederrick** [comment]
> @authorisation this is fixed with latest 1.2.0 you can close this btw.

I don't think this was fixed. I've asked multiple people on the official telegram group right after 1.2.0 was released, including one of the admins, and they said that it wasn't fixed yet. That was 2 days ago. Has it been fixed in the meantime? They said they would be working on it for the next update. 

Is it really working for you? Sharing longer videos through gallery with gallery override turned on exactly like I described in the images? And I don't mean being able to send it through the inbuilt camera roll as a one single snap. I mean sharing any video longer than 10 sec through gallery and being able to send it a regular snap divided into multiple 10 sec clips.

**Comment by halederrick** [comment]
That would be really nice if we have the option to split the video if we
want, because as it is right now it's pretty obvious to the receiver that
the snap is fake, since Snapchat always split the videos. It would be great
is SnapEnchance could do this so we don't have to use another app just for
that.

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/commit/0ba1eb4a8b067c8c8535409b3d432c912dc2e1a3
