### ISSUE TITLE
bug: - File path does not support Arabic script

### ISSUE THREAD

**Issue by MrTheenD** [rhunk/SnapEnhance#45]
### Description

When selecting "Add username to download path" it would rather pick the user's display name and set it as path name. However, sometimes the user's display name contains Arabic script, when downloading their snaps it would result in a path name with a space " " because it was that only character that was rendered as usable to the module. 

### Reproduction steps

```bash
1. Open module settings.
2. Under Media Manager, tap on Download Options.
3. Check "Add the username to the file path" . 
4. Download a snap from any user with Arabic script as their name and the issue would appear.
```

### Screenshots

```bash
[Screenshot](https://i.ibb.co/Pg4wYcG/Screenshot-20230605-211057-Gallery.jpg)
```

### Snapchat Version

12.36.0.53

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by rhunk** [comment]
fixed in https://github.com/rhunk/SnapEnhance/pull/81/commits/1e451c3f2f7ae332900641128a143496844fe3c8

**Comment by iBasim** [comment]
@rhunk @authorisation 
The problem persists. If the display name is in Arabic, the name of folder will be _ .

**Comment by TheVisual** [comment]
[app-1.2.1-armv8-debug.zip](https://github.com/rhunk/SnapEnhance/files/12256987/app-1.2.1-armv8-debug.zip)

@iBasim @MrTheenD Please confirm this is working it seems to be
